[package]
name = "hex_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chumsky = "0.10.1"
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
logos = "0.15.0"
rand = "0.9.1"
